In [1]:
import numpy as np

In [55]:
a=np.array([[1,2],[3,4],[5,6]])

Dimensions of array

In [8]:
a.ndim

2

Size of datatype of each element

In [54]:
a.itemsize

4

Change data type of each elelment

In [10]:
a=np.array([[1,2],[3,4],[5,6]], dtype=np.float64)

In [11]:
a.itemsize

8

In [12]:
a.size

6

In [13]:
a.shape

(3, 2)

In [16]:
a=np.array([[1,2],[3,4],[5,6]], dtype=complex)
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [17]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
np.arange(1,5)

array([1, 2, 3, 4])

In [20]:
np.arange(1,5,2)

array([1, 3])

In [21]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [24]:
a=np.array([[1,2],[3,4],[5,6]])
a.shape
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [23]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
u=a.ravel()
u

array([1, 2, 3, 4, 5, 6])

In [34]:
a.min()

1

In [35]:
a.max()

6

In [36]:
a.sum()

21

In [37]:
a.sum(axis=0)

array([ 9, 12])

In [38]:
a.sum(axis=1)

array([ 3,  7, 11])

In [39]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [40]:
np.std(a)

1.707825127659933

In [43]:
a=([[1,2],[3,4]])
b=([[5,6],[7,8]])

In [44]:
a

[[1, 2], [3, 4]]

In [45]:
b

[[5, 6], [7, 8]]

In [46]:
a+b

[[1, 2], [3, 4], [5, 6], [7, 8]]

In [47]:
np.add(a,b)

array([[ 6,  8],
       [10, 12]])

In [49]:
np.multiply(a,b)

array([[ 5, 12],
       [21, 32]])

In [51]:
np.dot(a,b)

array([[19, 22],
       [43, 50]])